### ISSUE TITLE
PI requires that values be padded to their bit-width

### ISSUE THREAD

**Issue by konne88** [p4lang/PI#531] opened 2021-02-02 01:06 UTC
PI calls `check_proto_bytestring` in a couple of places, which ensures that values are padded to their bit-width. This was the old required behavior, but the spec now also supports values that aren't padded [1]. Can we update PI to match the spec.

[1]: https://p4.org/p4runtime/spec/master/P4Runtime-Spec.html#sec-bytestrings

**Comment by smolkaj** [comment] 2021-02-05 14:54
@antoninbas, do you know if this can be fixed simply by removing all calls to `check_proto_bytestring`? Or will this require  more involved changes?

**Comment by antoninbas** [comment] 2021-02-05 18:36
@smolkaj you can make comment out all the calls, but that's not a fix. The implementation should be changed to perform the correct checks (the provided bytestring should still fit within the expected bitwidth, or it is an error). I think more changes are also required to provide read-write symmetry.


Duplicate of https://github.com/p4lang/PI/issues/454

**Closed** 2021-03-01 20:13 UTC
