### ISSUE TITLE
Adding an entry twice gives me error

### ISSUE THREAD

**Issue by adibrastegarnia** [p4lang/PI#296] opened 2018-02-04 01:38 UTC
Hi, 
When I try to I add a match-action rule entry in a table for the second time, it gives me the following error: 

File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 434, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, Error when adding match entry to target)>

Any suggestions?

**Comment by adibrastegarnia** [comment] 2018-02-04 02:28
I used this function:
def WriteTableEntry(self, table_entry, dry_run=False):
        request = p4runtime_pb2.WriteRequest()
        request.device_id = self.device_id
        update = request.updates.add()
        update.type = p4runtime_pb2.Update.INSERT
        update.entity.table_entry.CopyFrom(table_entry)
        if dry_run:
            print "P4 Runtime Write:", request
        else:
            self.client_stub.Write(request)

**Comment by jafingerhut** [comment] 2018-02-04 07:01
Are you trying to add the same key the second time, or a different one?  I believe an error is expected on any attempt to add a table entry with a key that is the same as a key that already exists in the table.

If the second key is different than the first, and not added earlier, then I don't know what to suggest next.

**Comment by adibrastegarnia** [comment] 2018-02-04 16:50
I am trying to add the same key the second time. Is there any specific reason to avoid it? Suppose this scenario: Suppose we have a network with two different subnet. We have three hosts (H1 (10.0.1.1), H2(10.0.1.2), H3(10.0.2.1). If we populate tables to support routing between H1 and H3 and later on we decide to add new values to support routing between H2 and H3 then it is not possible since the programmer is responsible to keep track of the previous entries.

**Comment by jafingerhut** [comment] 2018-02-04 18:51
Here I will have to defer to the knowledge of others working on the P4 Runtime API.  Hopefully one of them can respond to this issue.

There is definitely a way to add new table entries, modify existing table entries, and delete existing table entries.

I do not know whether the API calls for adding new table entries can also be used to modify existing table entries, or whether you are expected to use a different API for adding vs. modifying.

**Comment by adibrastegarnia** [comment] 2018-02-04 19:04
Thanks Andy for your response. Yes we should see what they say.

**Comment by antoninbas** [comment] 2018-02-05 18:20
As @jafingerhut mentioned this is the intended behavior. Duplicate table entries should be rejected by the P4 Runtime server. It is briefly mentioned in the P4 Runtime spec but not it should be called out when the `TableEntry` message is described:
```
- `ALREADY_EXISTS (6)`: The Write RPC failed because the entity already exists
  on the switch, e.g. in the case of a duplicate flow installation. This is
  typically caused by a client bug. The client should not retry the Write RPC
  unless the root-cause of the problem can be determined.
```

Your issue also shows that the p4lang P4 Runtime implementation is probably not correct - although I need to check - as it doesn't appear to return `ALREADY_EXISTS`.

Note that in your implementation, you are free to treat errors differently based on the error code. For example, if you don't want to propagate `ALREADY_EXISTS` errors to the application because you want to allow the application to install duplicate entries, feel free to do so and drop the error silently. Of course this assumes that the P4 Runtime implementation uses the correct error code...

I'm closing this issue, as I have now opened #297 and #298.

**Closed by antoninbas** 2018-02-05 18:20 UTC
