### ISSUE TITLE
How to get register ID from name

### ISSUE THREAD

**Issue by mohammedelazzab** [p4lang/PI#518] opened 2020-09-03 19:22 UTC
Hello , 
Is there a way to get regiser_id using pi_p4info APIs like `pi_p4info_counter_id_from_name` for counters ? 
The `pi_p4info_any_id_from_name` API requires a `pi_res_type_id_t` type but I could not find the type that corresponds to registers.

**Comment by antoninbas** [comment] 2020-09-03 20:24
There is currently no support for registers in PI (and thus in the P4Runtime implementation included in this repo, which relies on the PI library). If you want to contribute any part of the implementation, it would be very welcome.

Closing this issue since it is a duplicate of https://github.com/p4lang/PI/issues/376

**Closed by antoninbas** 2020-09-03 20:24 UTC
